const audio = [
  {
    artist: "Mendel Presscott",
    title: "The Baal Shem Tov _part 1",
    url: "audio/presscott/theBaalshem-tovpart1.mp3",
    description: "Historical context in which the Ba'al Shem Tov entered Jewish history",
    tags: "History Chassidim",
  },
  {
    artist: "Mendel Presscott",
    title: "The Baal Shem Tov _part 2",
    url: "audio/presscott/The-Ba'al-shem-tov-part2.mp3",
    description: "Historical context in which the Ba'al Shem Tov entered Jewish history",
    tags: "History Chassidim Miracles",
  },
  {
    artist: "Mendel Presscott",
    title: "Sfardim and Ashkazim",
    url: "audio/presscott/thedifferencebetweenSfardimandashkaziminthereapproachtomachlokes.mp3",
    description: "The difference between Sfardim and Ashkazim in their approach to machlokes",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "Early Rishonim _part 1",
    url: "audio/presscott/earlySpanishRishonimfourcaptives.mp3",
    description: "Early Spanish Rishonim, the four captive's",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "Early Rishonim _part 2",
    url: "audio/presscott/theearlyRishonimpart2.mp3",
    description: " ",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "The Baalei HaTosfos",
    url: "audio/presscott/TheBaaleiHaTosfos.mp3",
    description: "Discussion of the Mesorah - The Ba'alei HaTosfos",
    tags: "History Baalei HaTosfos",
  },
  {
    artist: "Mendel Presscott",
    title: "Rashi",
    url: "audio/presscott/Rashi.mp3",
    description: "Learn about the development and thought process that went into the making of a classic Torah commentary",
    tags: "History",
  },
  {
    artist: "Mendel Presscott",
    title: "The Gaonim",
    url: "audio/presscott/historyofthegaonim.mp3",
    description: "History of the Gaonim",
    tags: "History",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Shavous",
    url: "audio/shavous.mp3",
    description: "Why is it costomary to eat dairy on shavous",
    tags: "Holidays Shavous Matan Torah",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Bamidbar - Shavous",
    url: "audio/bamidbar-shavous.mp3",
    description: "Why didn't Ben Azzai need to fulfill the mitzvah of having children",
    tags: "Holidays Parsha Shavous Matan Torah",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Bechukoisai",
    url: "audio/bechukoisai.mp3",
    description: "I make plans to go places but I always end up at the study hall, Dovid Hamelech said to Hashem",
    tags: "Dovid Hamelech King God Hashem Study Hall Beis Medrash parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Tazria & Metzora _part 1",
    url: "audio/tazria-metzora1.mp3",
    description: "What's the logic that the listener to lashun harah gets a greater punishment than the teller?",
    tags: "Loshan Harah parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Tazria & Metzora _part 2",
    url: "audio/tazria-metzora2.mp3",
    description: "What's the logic that the listener to lashun harah gets a greater punishment than the teller?",
    tags: "Loshan Harah parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Pesach",
    url: "audio/pesach.mp3",
    description: "Everyday we have to remember leaving Egypt, what’s special about Pesach?",
    tags: "Leaving egypt yetzeas mitzrayim peshach holidays",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Behar",
    url: "audio/behar.mp3",
    description: "Understanding אונס with accountability",
    tags: "אונס parsha",
  },
  { artist: "Rabbi Kraznianski",
    title: "Purim",
    url: "audio/purim.mp3",
    description: "Reasons for sending mishloach manos",
    tags: "holidays",
  },
  { artist: "Rabbi Kraznianski",
    title: "Shemini",
    url: "audio/shemene.mp3",
    description: "Why where Aharon's children punished if they where under 20",
    tags: "parsha accountability twenty",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Mishpatim",
    url: "audio/mishpatim.mp3",
    description: "Being Jewish vrs the Torah's laws of majority",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Mishpatim",
    url: "audio/mishpatim-1.mp3",
    description: "Matan Torah and Jewish conversion",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Yisro",
    url: "audio/yisro.mp3",
    description: "Question if Moshe was considered a king",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Bo",
    url: "audio/bo.mp3",
    description: "Story of moshe and the king of Arabia",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "The Rambam",
    url: "audio/rambam.mp3",
    description: "The Rambam's birth and who was his teacher",
    tags: "shemos chaf teves yehudah hacohen yosef halevi iben megash remegash tzadik rif",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Toldos",
    url: "audio/Rabbi_krav_toldus.mp3",
    description: "Did Yitzchak know that Esuv was up to no good?",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vayera",
    url: "audio/Rabbi_kraz_vaera.mp3",
    description: " ",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Yud Tes Kislev",
    url: "audio/Rabbi_Kraz_pre_Yud_tes_kisslev.mp3",
    description: " ",
    tags: "holidays chassidish farbrengen",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Lech Lecha",
    url: "audio/Rabbi_kraz_lechlecha.mp3",
    description: "Is a father obligated to circumcise his son once the son turns thirteen",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Sukkos",
    url: "audio/Rabbi_kraz_suchos.mp3",
    description: "Were the Jews in the desert surrounded by clouds or actual Sukkos",
    tags: "Holidays",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Rosh Hashana",
    url: "audio/Rabbi_kraz_rush_hashana.mp3",
    description: "Is it allowed to fast on Rosh Hashana or not",
    tags: "Holidays",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Ki Savo",
    url: "audio/Rabbi_kraz_ke_savo.mp3",
    description: "Why did the Rabbis institute blessings before doing mitzvos",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Ki Savo",
    url: "audio/Rabbi_kraz_chai_elul_ke_savo.mp3",
    description: "Blessings on mitzvos, are they part of the mitzvos or mitzvos themselves",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Ki Seitzei",
    url: "audio/Rabbi_kraz_ke_tetze.mp3",
    description: "The reasoning behind the argument of 40 and 39 lashes",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Ki Seitzei",
    url: "audio/Rabbi_kraz_rushashana_ke_tzetze.mp3",
    description: "Do we punish someone now for future actions",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Shoftim",
    url: "audio/Rabbi_kraz_shuftim.mp3",
    description: "Eglah arufah",
    tags: "parsha revenge worms",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Shoftim",
    url: "audio/Rabbi_kraz_shuftim_2.mp3",
    description: "The seven Nations were kicked out of Israel for partaking in sorcery etc. why was this an issue for them?",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vaeschanan",
    url: "audio/Rabbi_kraz_veschanun.mp3",
    description: "A father has an obligation to teach his son Torah",
    tags: "parsha mitzvas aseh coerce reward beis din tzedakah",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vayeishev",
    url: "audio/vayeshev.mp3",
    description: "Yosef's brothers sell him and the connection to the asara harugei malchus",
    description: "The asara harugei malchus and their connection to the selling of Yosef by his brothers",
    tags: "parsha 10 ten martyrs shevatim tribs measure for measure middah keneged middah",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Miketz",
    url: "audio/meketz.mp3",
    description: "What was the mistake the Shevatim made in Judging Yosef",
    tags: "parsha Judge Judging",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Miketz",
    url: "audio/meketz_2.mp3",
    description: " ",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vayechi",
    url: "audio/vayechi.mp3",
    description: " ",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vayechi",
    url: "audio/vayechi_2.mp3",
    description: " ",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Vayechi",
    url: "audio/Vayechi_3.mp3",
    description: " ",
    tags: "parsha",
  },
  {
    artist: "Rabbi Kraznianski",
    title: "Kebud Av",
    url: "audio/kebud_av.mp3",
    description: " ",
    tags: "parsha",
  },
];










